# Generated by Django 4.1.4 on 2022-12-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityID', models.IntegerField()),
                ('regionID', models.IntegerField()),
                ('nameAR', models.CharField(max_length=50)),
                ('nameEN', models.CharField(max_length=50)),
            ],
        ),
    ]
