# Generated by Django 4.1.4 on 2022-12-08 16:09

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='centerCoordinate',
            field=jsonfield.fields.JSONField(default=(0.0, 0, 0)),
            preserve_default=False,
        ),
    ]
