# Generated by Django 4.1.4 on 2022-12-08 17:37

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_remove_city_centercoordinate'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='centerCoordinate',
            field=jsonfield.fields.JSONField(default=(28.41463997, 36.53387003)),
            preserve_default=False,
        ),
    ]
