# Generated by Django 4.1.4 on 2022-12-08 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_city_centercoordinate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='centerCoordinate',
            new_name='center',
        ),
    ]
