# Generated by Django 4.1.4 on 2022-12-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_remove_city_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='center',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
