# Generated by Django 4.1.4 on 2022-12-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_city_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='center',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
