# Generated by Django 4.1.4 on 2022-12-08 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0014_alter_city_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='center',
        ),
    ]
