# Generated by Django 4.1.4 on 2022-12-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0015_remove_city_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(decimal_places=2, default=28.41463997, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(decimal_places=2, default=28.41463997, max_digits=15),
            preserve_default=False,
        ),
    ]
