# Generated by Django 4.1.4 on 2022-12-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0016_city_latitude_city_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
    ]
