# Generated by Django 4.1.4 on 2022-12-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0019_users_users_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_cities',
            name='latitude',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users_cities',
            name='longitude',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users_cities',
            name='nameAR',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users_cities',
            name='nameEN',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
